packages:
  - 'packages/*'
  - 'packages/shared/*'
  - 'packages/business/*'
  - 'packages/platform/*'
  - 'packages/platform/ai/*'
  - 'packages/platform/flow/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'
overrides:
  is-generator-function: '1.1.0'
