packages:
  - 'packages/*'
  - 'packages/editor/*'
  - 'packages/flow/*'
  - 'packages/shared/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'
overrides:
  is-generator-function: '1.1.0'
