import type { WidgetConfig } from '../base/types'

export const areaChartConfig: WidgetConfig = {
  name: 'FgAreaChart',
  displayName: '面积图',
  type: 'area-chart',
  description: '面积图，用于展示数据随时间的变化趋势',
  author: 'yangdongnan',
  defaultStyle: { width: '100%', height: '400px' },
  defaultProps: {
    staticData: [
      { category: '1月', value: 120 },
      { category: '2月', value: 200 },
      { category: '3月', value: 150 },
      { category: '4月', value: 80 },
      { category: '5月', value: 170 },
    ] as Record<string, unknown>[],
    xField: 'category',
    yField: 'value',
    xAxisName: '',
    yAxisName: '',
    title: '',
    showLegend: true,
    legendPosition: 'bottom',
    showTooltip: true,
    showLabel: false,
    colorScheme: 'default',
    customColors: ['#5470c6', '#91cc75', '#fac858', '#ee6666', '#73c0de'] as string[],
    smooth: true,
    areaOpacity: 0.6,
    animation: true,
    rawOption: null as Record<string, unknown> | null,
  },
  exposedValues: [
    { key: 'loading', type: 'boolean', description: '加载状态' },
    { key: 'chartData', type: 'array', description: '图表数据' },
  ],
  configPanels: ['api', 'variables'],
  receivableEvents: [
    { name: 'refresh', description: '重新加载数据' },
    { name: 'set-data', description: '设置图表数据', params: { data: '数据数组' } },
  ],
  propertyPanel: {
    basic: ['label'],
    style: ['margin', 'padding', 'backgroundColor', 'borderRadius'],
    props: [
      { key: 'staticData', label: '静态数据', type: 'array-editor', fields: [
        { key: 'category', label: '分类', type: 'text' },
        { key: 'value', label: '值', type: 'number' },
      ]},
      { key: 'xField', label: 'X 轴字段', type: 'text', placeholder: '如: category' },
      { key: 'yField', label: 'Y 轴字段', type: 'text', placeholder: '如: value' },
      { key: 'title', label: '图表标题', type: 'text' },
      { key: 'showLegend', label: '显示图例', type: 'switch', default: true },
      { key: 'showTooltip', label: '显示提示', type: 'switch', default: true },
      { key: 'showLabel', label: '显示标签', type: 'switch', default: false },
      { key: 'smooth', label: '平滑曲线', type: 'switch', default: true },
      { key: 'areaOpacity', label: '区域透明度', type: 'number', default: 0.6 },
      { key: 'animation', label: '动画', type: 'switch', default: true },
      { key: 'colorScheme', label: '颜色主题', type: 'select', options: [
        { label: '默认', value: 'default' },
        { label: '暗色', value: 'dark' },
        { label: '浅色', value: 'light' },
      ]},
      { key: 'customColors', label: '自定义颜色', type: 'color-array' },
      { key: 'rawOption', label: '高级配置 (JSON)', type: 'json' },
    ],
  },
}
