import type { WidgetConfig } from '../base/types'
export const dialogConfig: WidgetConfig = {
  name: 'FgDialog',
  displayName: '弹窗容器',
  description: '弹窗容器，支持编辑模式和微前端模式，可配置标题、宽度、按钮',
  author: 'yangdongnan',
  defaultStyle: {},
  defaultProps: {
    title: '弹窗标题',
    width: '600px',
    confirmText: '确定',
    cancelText: '取消',
    destroyOnClose: true,
    contentMode: 'edit' as const,
    microappMode: 'iframe' as const,
    showFooter: true,
    closeOnClickModal: false,
    draggable: true,
    showFullscreenBtn: true,
  },
  propertyPanel: {
    basic: [
      { key: 'title', label: '标题', type: 'input', default: '弹窗标题' },
      { key: 'width', label: '宽度', type: 'input', default: '600px' },
      { key: 'confirmText', label: '确认按钮文字', type: 'input', default: '确定' },
      { key: 'cancelText', label: '取消按钮文字', type: 'input', default: '取消' },
      { key: 'destroyOnClose', label: '关闭时销毁', type: 'switch', default: true },
      { key: 'showFooter', label: '显示底部按钮', type: 'switch', default: true },
      { key: 'closeOnClickModal', label: '点击遮罩关闭', type: 'switch', default: false },
      {
        key: 'contentMode',
        label: '内容模式',
        type: 'select',
        options: [
          { label: '编辑模式', value: 'edit' },
          { label: '微应用模式', value: 'microapp' },
        ],
        default: 'edit',
      },
      {
        key: 'microappMode',
        label: '嵌入模式',
        type: 'select',
        options: [
          { label: 'iframe（轻量）', value: 'iframe' },
          { label: 'qiankun（完整）', value: 'qiankun' },
        ],
        default: 'iframe',
        visibleOn: "props.contentMode === 'microapp'",
      },
      {
        key: 'microappApp',
        label: '子应用',
        type: 'select',
        options: [
          { label: '编辑器', value: 'editor' },
          { label: '流程', value: 'flow' },
          { label: 'AI', value: 'ai' },
        ],
        default: '',
        placeholder: '选择子应用',
        visibleOn: "props.contentMode === 'microapp' && props.microappMode === 'qiankun'",
      },
      {
        key: 'publishId',
        label: '发布 ID',
        type: 'remote-select',
        remoteUrl: '/schemas/published',
        labelField: 'name',
        valueField: 'publishId',
        default: '',
        placeholder: '选择已发布的 Schema',
        visibleOn: "props.contentMode === 'microapp' && props.microappMode === 'iframe'",
      },
      {
        key: 'microappBaseUrl',
        label: '自定义 URL',
        type: 'input',
        default: '',
        placeholder: '留空使用默认地址',
        visibleOn: "props.contentMode === 'microapp' && props.microappMode === 'iframe'",
      },
    ],
    style: [],
    props: [
      { key: 'draggable', label: '可拖拽', type: 'switch', default: true },
      { key: 'showFullscreenBtn', label: '显示全屏按钮', type: 'switch', default: true },
    ],
  },
  exposedValues: [
    { key: 'visible', type: 'boolean', description: '弹窗是否可见' },
    { key: 'dialogData', type: 'object', description: '弹窗表单数据' },
  ],
  eventTargets: [
    { id: 'confirm', label: '确认按钮', description: '点击确认时触发' },
    { id: 'cancel', label: '取消按钮', description: '点击取消时触发' },
  ],
  configPanels: ['events', 'variables'],
  receivableEvents: [
    { name: 'open', description: '打开弹窗' },
    { name: 'close', description: '关闭弹窗' },
  ],
}
